version: "3.8"
services:
  client:
    image: "ethernetz/fibonacci-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "ethernetz/fibonacci-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PGUSER
      - PG_HOST=$PGHOST
      - PG_DATABASE=$PGDATABASE
      - PG_PORT=$PGPORT
      - AWS_REGION=us-east-1
      - AWS_DBSECRETNAME=rds!db-8b22adc4-b5b9-4072-a5f1-279a3fbb858b
  worker:
    image: "ethernetz/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: "ethernetz/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
