version: "3.8"
services:
  client:
    image: "ethernetz/fibonacci-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "ethernetz/fibonacci-api"
    mem_limit: 128m
    hostname: api
    secrets:
      - my_secret
      # - file_secret
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PGUSER: $OTHER_PGUSER
      PGHOST: $OTHER_PGHOST
      PGDATABASE: $OTHER_PGDATABASE
      PGPASSWORD: $OTHER_PGPASSWORD
      PGPORT: $OTHER_PGPORT
  worker:
    image: "ethernetz/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: "ethernetz/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

secrets:
  # file_secret:
  #   file: ./super_duper_secret.txt
  my_secret:
    name: "arn:aws:secretsmanager:us-east-1:676753199952:secret:rds!db-8b22adc4-b5b9-4072-a5f1-279a3fbb858b-7HePV5"
    external: true
