version: "3"
services:
  client:
    image: "ethernetz/fibonacci-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "ethernetz/fibonacci-api"
    mem_limit: 128m
    hostname: api
    secrets:
      - PGPASSWORD
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
  worker:
    image: "ethernetz/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "ethernetz/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

secrets:
  PGPASSWORD:
    name: "arn:aws:rds:us-east-1:676753199952:db:fibonacci-values-db"
    external: true
