version: "3.8"
services:
  client:
    image: "ethernetz/fibonacci-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "ethernetz/fibonacci-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$OTHER_PGUSER
      - PGHOST=$OTHER_PGHOST
      - PGDATABASE=$OTHER_PGDATABASE
      - PGPASSWORD=$OTHER_PGPASSWORD
      - PGPORT=$OTHER_PGPORT
      - AWS_region=us-east-1
  worker:
    image: "ethernetz/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
  nginx:
    image: "ethernetz/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
