name: Run tests, build, push, and deploy
on:
  push:
    branches:
    - master

jobs:
  run_tests:
    name: Run test suite
    uses: ./.github/workflows/run-test-suite.yaml

  push_client_to_docker:
    name: Push client to Docker
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ethernetz/fibonacci-client:latest

  push_api_to_docker:
    name: Push api to Docker
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: ethernetz/fibonacci-api:latest

  push_nginx_to_docker:
    name: Push nginx to Docker
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ethernetz/fibonacci-nginx:latest

  push_worker_to_docker:
    name: Push worker to Docker
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        file: ./worker/Dockerfile
        push: true
        tags: ethernetz/fibonacci-worker:latest

  deploy_to_eb:
    name: Deploy to Elastic Beanstalk
    needs: [push_client_to_docker, push_api_to_docker, push_nginx_to_docker, push_worker_to_docker]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Generate deployment package
      run: zip deploy.zip docker-compose.yml
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        application_name: fibonacci
        environment_name: Fibonacci-dev
        version_label: ${{ github.run_number }}
        version_description: ${{ github.SHA }}
        region: us-east-1
