name: Run tests and deploy to AWS
on:
  push:
    branches:
    - master

jobs:
  client_tests:
    name: Run client test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run client tests
      run: CI=true docker-compose -f docker-compose-dev.yml up --build client-tests

  deploy_client_to_docker:
    name: Deploy client to docker
    needs: client_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ethernetz/fibonacci-client:latest

  deploy_api_to_docker:
    name: Deploy api to docker
    needs: client_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: ethernetz/fibonacci-api:latest

  deploy_nginx_to_docker:
    name: Deploy nginx to docker
    needs: client_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        file: ./nginx/Dockerfile
        push: true
        tags: ethernetz/fibonacci-nginx:latest

  deploy_worker_to_docker:
    name: Deploy worker to docker
    needs: client_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        file: ./worker/Dockerfile
        push: true
        tags: ethernetz/fibonacci-worker:latest
