name: Run tests

on:
  pull_request:
    branches:
    - master

jobs:
  client_tests:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run client tests
      run: CI=true docker-compose -f docker-compose-dev.yml up --build client-tests
